apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false
    discovery.type: single-node
    ELASTIC_PASSWORD: "123456"
  redis.conf: |
   
  movie-app-config.properties: |
    SERVER_PORT=8000
    
