apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieapp-deployment
  labels:
    app: movie-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
      - name: movie-app
        image: movie_image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
